### ISSUE TITLE
Write README

### ISSUE THREAD

**Issue by Genki-S** [ENIXER/DominionShuffler#1]
:smirk: 

contents:
- What is this?
- Setup
- Contribution

**Comment by junk0612** [comment]
Thank you. I wrote README.md considering your opinion.
Is it enough?

**Comment by Genki-S** [comment]
PERFECT!!! :tada: 

I would add a link to dominion explanation (e.g. http://en.wikipedia.org/wiki/Dominion_(card_game) ), but it's up to you :+1:
